Added COR1009, EEE1002
RangHo/sogang-courses pull request #4
Opened 2021-04-25 04:27 UTC by charlielee206

전자과 전용 컴퓨팅사고력 (COR1009), C언어기초 (EEE1002) 추가하였습니다.

2021-04-25 04:29 UTC, charlielee206 commented
깃허브가 익숙하지 않아서 커밋 히스토리가 뒤죽박죽인 점 양해부탁드립니다. 또한, 동영상 파일 관련 메일 보내드렸습니다.

2021-05-21 11:43 UTC, RangHo requested changes
README 파일에 남긴 것과 같이 파일 확장자 변경 부탁드리고, 가능하면 소스코드에 `clang-format`도 적용해 주시면 감사하겠습니다. 포맷 파일은 [여기](CSE2003/.clang-format)에서 확인해 주세요!

만약 사용법을 잘 모르신다면 제가 나중에 폰으로도 적용할 수 있으니 코멘트 남겨주시면 추후 제가 수정하겠습니다!

2021-05-21 11:43 UTC, RangHo commented on COR1009/README.md
> +<br>수업 당시 제출 양식이 .txt 파일이어서 깃허브 리포에도 .txt 파일로 되어있습니다. 이 점 양해부탁드립니다. <br>
수업 당시 제출 양식이 일반 텍스트였던 점은 이해하나 코드 가독성을 위해 아두이노 스케치는 `.ino`로, 이외 C/C++ 소스코드는 각각 `.c`와  `.cpp`로 바꿔 주시면 감사하겠습니다! 이 리포는 어디까지나 "참고"를 위해서니까요 😉

2021-05-25 06:28 UTC, charlielee206 commented on COR1009/README.md
> +<br>수업 당시 제출 양식이 .txt 파일이어서 깃허브 리포에도 .txt 파일로 되어있습니다. 이 점 양해부탁드립니다. <br>
아두이노 코드의 .txt 파일은 .ino 파일로 바꾸었습니다만은, 제목에 한글이 있기 때문에 아두이노 기본 IDE 에서 열 수 없습니다. (이 이유 때문에 과제 제출도 .txt 파일로 제출했습니다.) 이 사항에 대해서 Readme 에 작성하였습니다.

아두이노 및 C 코드 모두 포매팅을 하였습니다만은, 항상 기본 포매팅만 사용해와서 제대로 적용이 되었는지 모르겠습니다.  이 점 확인해주시면 감사하겠습니다.
죄송합니다...

2021-05-25 10:33 UTC, RangHo approved these changes

2021-05-25 10:33 UTC, merged